### ISSUE TITLE
Need help writing documentation?

### ISSUE THREAD

**Issue by ttoommxx** [unicurses/unicurses#35]
Hi developer,
thank you for your amazing work! I was wondering if you needed some help writing more exhaustive documentation. Most of the functions do translate 1to1 to curses, but it would still be nice to have a complete and consistent wiki that explains one by one. Let me know if you want help with it, and if so would you mind sending me a draft of what you have, as some of these functions I just have no clue what they do at all?

**Comment by GiorgosXou** [comment]
👋 Hi there!

> thank you for your amazing work! 

First off, thanks for appreciating our work! 🤗

> it would still be nice to have a complete and consistent wiki that explains one by one.

**Yeah! I'd be more than happy to accept a pull request, so...** feel free to do so!  TBH Since I've started maintaining this repo,  I've done very little about the docummentation ngl 😅... so, this would be really nice if would be done properly.

>  would you mind sending me a draft of what you have, as some of these functions I just have no clue what they do at all?

**Unfortunatly I don't have any draft. But,** *(as you might already have found out)* you can see what each function does either by looking in the [man-page](https://linux.die.net/man/3/ncurses) or by checking the comments above each function in the source codes of [pdcurses](https://github.com/wmcbrine/PDCurses) or [ncurses](https://github.com/mirror/ncurses). **If you struggle with any, just skip it** or just post it here and will figure it out.

**Comment by ttoommxx** [comment]
Is there a way I can reach out to you faster? Discord etc..

**Comment by GiorgosXou** [comment]
Sure, add me on discord `ego3157`

**Comment by GiorgosXou** [comment]
Discord disabled my account *(probably because I was playing around with their private api)*. @ttoommxx add me on `spiounos_36582` if you want
