### ISSUE TITLE
PIP support

### ISSUE THREAD

**Issue by hotlittlewhitedog** [unicurses/unicurses#9]
Hi Chiel :)

I use unicurses for Linux and later for Windows, Mac OS.
Actually I'm playing with `pipenv` and I see that `pip install unicurses` or `pip install UniCurses` does not work. The package exist on PyPi.org but the download reference to sourceforge seems outdated (repo of Michael Kamensky).

As I will create a pip of my application, I think it's a good step to have all the dependencies on PyPi. 

Can you create a package on PyPi, so we can import unicurses? :)
Rem: also think at the support of Windows with Pdcurses. 
Maybe you add both in a single package.

Thanks a lot.

**Comment by Chiel92** [comment]
I'm not actively maintaining this project. If you really want this and are willing to put in the work, feel free to clone it and/or make a pull request.

**Comment by GiorgosXou** [comment]
# [Done ✔️ `pip install uni-curses`](https://github.com/unicurses/unicurses#importing-unicurses)

**Comment by hotlittlewhitedog** [comment]
@GiorgosXou Hi Giorgos, 

Finally I migrated to Uni-Curses (your lib is now mature).
I got only 1 bug on my side (I closed a panel before the window!) and 2 getstrings where you included the utf8 encoding. 

Works like a charm ❤️ 
By doing this I was able to finally create an appImage that doesn't crash on a color_pair :)

. PyPI: https://pypi.org/project/sonofman/ (>= 3.8.0)
. AppImage: https://github.com/hotlittlewhitedog/BibleMultiTheSonOfMan-AppImage

**Comment by GiorgosXou** [comment]
<img width="166" height="34" alt="Image" src="https://github.com/user-attachments/assets/786ee1f5-46cc-43e8-b924-5d7154ee2d67" />

@hotlittlewhitedog Love it.

> Finally I migrated to Uni-Curses (your lib is now mature).

Thanks -- though I'm just a maintainer. I have to give credit you know ;-) 

> Works like a charm ❤️

Yep, looked into the source code, and tested it on my device too. Here's my honest feedback, and things I'd love to see:

-  ***Add Vim-like motions\mode:***
- - `K` for `KEY_ENTER`\`10`
- - `k` for `KEY_UP` and `j` for `KEY_DOWN`
- - `h` for `KEY_LEFT` and `l` for `KEY_RIGHT`
- - `y` to copy the verse `Y` for `chapter`, `c` to `clear`
- - `/` to search everywhere
- ***Fixes, improvemetns etc:***
- - Use `?` to diplay `Articles > Keys` 
- - Remove `som_unicurses.py` *(I think you forgot to)*
- - Consider [KEY_RESIZE](https://github.com/GiorgosXou/TUIFIManager/blob/d619c5dc54b1a321d19ff45cdfd20c2ad58e4736/TUIFIManager/__main__.py#L53-L55) when terminal resizes
- - Consider a python-dictionary like [this](https://github.com/GiorgosXou/TUIFIManager/blob/d619c5dc54b1a321d19ff45cdfd20c2ad58e4736/TUIFIManager/__init__.py#L792-L858) + [this](https://github.com/GiorgosXou/TUIFIManager/blob/d619c5dc54b1a321d19ff45cdfd20c2ad58e4736/TUIFIManager/__init__.py#L1866) instead of `if-else`-statements at your `main()`
- - A Greek version of bible ?

I might take a look again at some other time. Hope it helps, keep being possitive! and feel free to bother 😅  me for help any time!

**Comment by hotlittlewhitedog** [comment]
@GiorgosXou  Thanks a lot for your great suggestions 👍 
There are a greek & hebrew Bibles in The Light (Biblemulti.org) with interlinear and lexicons ^^
All is a question of time about adding all functionalities in all apps using different languages 😫
